version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.24.1
    restart: on-failure:0
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: './data'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'estimate-service-key'
      AUTHENTICATION_APIKEY_USERS: 'estimate-service'
      AUTHORIZATION_ADMINLIST_ENABLED: 'true'
      AUTHORIZATION_ADMINLIST_USERS: 'estimate-service'
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - estimate-network

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: '0'
      # Для русского языка лучше использовать multilingual модель
    networks:
      - estimate-network

volumes:
  weaviate_data:
    driver: local

networks:
  estimate-network:
    driver: bridge
