version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: estimate_service
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - estimate-network

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    networks:
      - estimate-network

volumes:
  postgres_data:

networks:
  estimate-network:
    driver: bridge
